version: '3'
services:
  php:
    image: php:7.2.3-fpm-stretch
    volumes:
    - ../..:/app
  nginx:
    image: nginx:1.12.2
    ports:
    - "8080:80"
    volumes:
    - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    - ../..:/app
